### ISSUE TITLE
Unknown command.  Type "/help" for help

### ISSUE THREAD

**Issue by fossinating** [Krymonota/BungeeNCPNotify#9]
I have put the plugin in the spigot plugin folder, and it seems to not know of the /notify command.

I am running Spigot 1.11.2.
NoCheatPlus is running without error on build 1080 from Jenkins.

I am getting this error message: 

> [BungeeNCPNotify] Plugin BungeeNCPNotify v1.0 generated an exception while executing task 622
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at com.craftapi.bungeencpnotify.service.Metrics.postPlugin(Metrics.java:335) ~[?:?]
        at com.craftapi.bungeencpnotify.service.Metrics.access$400(Metrics.java:57) ~[?:?]
        at com.craftapi.bungeencpnotify.service.Metrics$1.run(Metrics.java:223) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]

How would you recommend me to try fixing this error?

**Comment by Krymonota** [comment]
This plugin is currently not officially supported anymore, but this error seems to be caused by the Metrics feature. I recommend you to try disabling the Metrics feature in the plugin configuration.
